## Tensorの基礎

In [16]:
import torch
import numpy as np

### tensor作成

In [18]:
my_list = [1, 2, 3, 4]
tensor_from_list = torch.tensor(my_list, dtype=torch.float64)
tensor_from_list

tensor([1., 2., 3., 4.], dtype=torch.float64)

In [19]:
zeroes_tensor = torch.zeros((2, 3))
zeroes_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [20]:
ones_tensor = torch.ones((2, 3))
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [21]:
eye_tensor = torch.eye(3)
eye_tensor

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [22]:
torch.manual_seed(42)   # 乱数固定
random_tensor = torch.rand((2, 3))
random_tensor

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

### tensorの操作

In [25]:
tensor_example = torch.rand((2, 3, 4))
tensor_example

tensor([[[0.9516, 0.0753, 0.8860, 0.5832],
         [0.3376, 0.8090, 0.5779, 0.9040],
         [0.5547, 0.3423, 0.6343, 0.3644]],

        [[0.7104, 0.9464, 0.7890, 0.2814],
         [0.7886, 0.5895, 0.7539, 0.1952],
         [0.0050, 0.3068, 0.1165, 0.9103]]])

In [26]:
# 転置
permuted_tensor = torch.permute(tensor_example, (1, 0, 2))
permuted_tensor

tensor([[[0.9516, 0.0753, 0.8860, 0.5832],
         [0.7104, 0.9464, 0.7890, 0.2814]],

        [[0.3376, 0.8090, 0.5779, 0.9040],
         [0.7886, 0.5895, 0.7539, 0.1952]],

        [[0.5547, 0.3423, 0.6343, 0.3644],
         [0.0050, 0.3068, 0.1165, 0.9103]]])

In [27]:
# 転置(2軸の入れ替え)
transposed_tensor = torch.transpose(tensor_example, 0, 1)   # rank0とrank1を入れ替え
transposed_tensor

tensor([[[0.9516, 0.0753, 0.8860, 0.5832],
         [0.7104, 0.9464, 0.7890, 0.2814]],

        [[0.3376, 0.8090, 0.5779, 0.9040],
         [0.7886, 0.5895, 0.7539, 0.1952]],

        [[0.5547, 0.3423, 0.6343, 0.3644],
         [0.0050, 0.3068, 0.1165, 0.9103]]])

In [28]:
# reshape
reshaped_tensor = torch.reshape(tensor_example, (6, 4))
reshaped_tensor

tensor([[0.9516, 0.0753, 0.8860, 0.5832],
        [0.3376, 0.8090, 0.5779, 0.9040],
        [0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814],
        [0.7886, 0.5895, 0.7539, 0.1952],
        [0.0050, 0.3068, 0.1165, 0.9103]])

In [34]:
# メモリが連続か確認
tensor_example.is_contiguous()

True

In [38]:
# view(同様にreshapeするがメモリが連続の場合のみ)
viewed_tensor = tensor_example.view(-1)
viewed_tensor

tensor([0.9516, 0.0753, 0.8860, 0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547,
        0.3423, 0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895,
        0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103])

In [36]:
# 多次元を1次元に
flatten_tensor = torch.flatten(tensor_example)
flatten_tensor

tensor([0.9516, 0.0753, 0.8860, 0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547,
        0.3423, 0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895,
        0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103])

In [41]:
# squeeze
tensor_example = torch.tensor([[[1], [2], [3]]])
print(tensor_example.shape)
squeezed_tensor = torch.squeeze(tensor_example)
print(squeezed_tensor.shape)

torch.Size([1, 3, 1])
torch.Size([3])


In [44]:
# unsqueeze
print(tensor_example.shape)
unsqueezed_tensor = torch.unsqueeze(tensor_example, 0)
print(unsqueezed_tensor.shape)

torch.Size([1, 3, 1])
torch.Size([1, 1, 3, 1])


### tensorの便利関数

In [45]:
tensor_example = torch.rand((2, 3))
tensor_example

tensor([[0.6440, 0.7071, 0.6581],
        [0.4913, 0.8913, 0.1447]])

In [46]:
# 合計
torch.sum(tensor_example)

tensor(3.5366)

In [47]:
# 平均
torch.mean(tensor_example)

tensor(0.5894)

In [48]:
# 平方根
torch.sqrt(tensor_example)

tensor([[0.8025, 0.8409, 0.8113],
        [0.7009, 0.9441, 0.3805]])

In [49]:
# 中身を取り出す
torch.sum(tensor_example).item()

3.53660249710083

### 行列の演算

In [50]:
# 加減+要素ごとの乗除(アダマール積)
a = torch.rand((3, 3))
b = torch.rand((3, 3))

In [51]:
a + b

tensor([[0.7333, 1.1085, 1.3208],
        [1.3089, 0.7406, 0.3999],
        [1.0235, 0.3673, 0.9043]])

In [52]:
a - b

tensor([[ 0.3297, -0.7910, -0.0124],
        [-0.6533,  0.5658,  0.3918],
        [ 0.8059,  0.0400, -0.5007]])

In [53]:
a * b

tensor([[0.1072, 0.1507, 0.4361],
        [0.3216, 0.0571, 0.0016],
        [0.0995, 0.0333, 0.1418]])

In [54]:
a / b

tensor([[ 2.6339,  0.1671,  0.9813],
        [ 0.3341,  7.4770, 97.4484],
        [ 8.4057,  1.2444,  0.2873]])

In [55]:
# 内積
torch.mm(a, b)

tensor([[0.3342, 0.6257, 0.8145],
        [0.7501, 0.4332, 0.4993],
        [0.4063, 0.9195, 0.7524]])

In [56]:
torch.matmul(a, b)

tensor([[0.3342, 0.6257, 0.8145],
        [0.7501, 0.4332, 0.4993],
        [0.4063, 0.9195, 0.7524]])

In [57]:
a @ b

tensor([[0.3342, 0.6257, 0.8145],
        [0.7501, 0.4332, 0.4993],
        [0.4063, 0.9195, 0.7524]])